config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  # Solo para usuarios autenticados (todo el sitio)


  authenticated :user do
    get 'calendario/index'
    get "/clientes/:cliente_id/redes/:red_id/posts", to: "posts#by_red"
    get "/posts", to: "posts#index"
    # get "/posts.json", to: "posts#index_json"
    resources :clientes do
      resources :redes do
        resources :posts
      end
    end
    resources :redes
    post '/posts/create/ig', to: 'posts#create_ig'
    put '/posts/:id/edit/ig', to: 'posts#update_ig'
    delete '/posts/:id/delete/ig', to: 'posts#destroy_ig'
    post "/post_test/:id", to: "posts#post_test"
    post "/post_imagen/:id", to: "posts#imagen_url"
    root to: "clientes#index" # , as: :authenticated_root
    # mount Sidekiq::Web => "/sidekiq" # monitoring console
  end

  # Si no esta autenicado
  root to: redirect("/users/sign_in")

  # Saco esta regla porque trae conflictos con los URL de blobs de Active Storage
  # match "*unmatched", to: "errors#route_not_found", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  created_at :datetime         not null
#  id         :bigint(8)        not null, primary key
#  nombre     :string           default(""), not null
#  updated_at :datetime         not null
#

class Cliente < ApplicationRecord
  has_many :redes, dependent: :destroy
  has_many :posts, through: :redes

  has_one_attached :logo

  validates :nombre, presence: true
end

app/controllers/clientes_controller.rb
# == Schema Information
#
# Table name: clientes
#
#  created_at :datetime         not null
#  id         :bigint(8)        not null, primary key
#  nombre     :string           default(""), not null
#  updated_at :datetime         not null
#

require "net/http"
require "open-uri"
# require "net/http/post/multi+part"

class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[show edit update destroy]

  # GET /clientes
  def index
    @clientes = Cliente.all
    @user = current_user.id

    app_secret = "c7166257539efd50cf8f523de38618cd"
    app_id = "979922088853971"

    # @oauth = Koala::Facebook::OAuth.new(app_id, app_secret, 'https://127.0.0.1:3000')
    # @urlforauth = @oauth.url_for_oauth_code(permissions: "publish_actions")
    # redirect_to(@oauth.url_for_oauth_code)
    # @user = User.find(2).email
    # @test_result = post_test
  end

  # GET /clientes/1
  def show
    # @redes = @cliente.redes
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  def create
    @cliente = Cliente.new(cliente_params)
    @cliente.logo.attach(cliente_params['logo'])

    if @cliente.save
      redirect_to @cliente, notice: "Cliente fue creado satisfactoriamente."
    else
      render :new
    end
  end

  # PATCH/PUT /clientes/1
  def update
    if @cliente.update(cliente_params)
      redirect_to @cliente, notice: "Cliente fue guardado satisfactoriamente."
    else
      render :edit
    end
  end

  # DELETE /clientes/1
  def destroy
    @cliente.destroy
    redirect_to clientes_url, notice: "Cliente fue eliminado satisfactoriamente."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def cliente_params
    params.require(:cliente).permit(:nombre, :logo)
  end
end

app/views/clientes/_form.html.erb
<%= bootstrap_form_for(@cliente) do |f| %>

  <%= f.alert_message "Han ocurrido los siguientes problemas:" %>

  <%= f.text_field :nombre %>

  <%= f.file_field :logo %>

  <%= f.primary %>
  <%= link_to "Atrás", clientes_path, class: "btn btn-link" %>

<% end %>

app/views/clientes/edit.html.erb
<% provide(:title, "Editando cliente") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/clientes/index.html.erb
<% provide(:title, "Lista de clientes") %>


<div class="post_test">
  <p><%= @test_result %></p>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th></th>
    <th>Nombre</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @clientes.each do |cliente| %>
    <tr>

      <td>
        <%= link_to cliente do %>
          <%= cliente.nombre %>
        <% end %>
      </td>
      <td>
        <div class="btn-group">
          <%= link_to cliente, class: "btn btn-xs btn-default" do %>

            <%= fa_icon("eye", text: "Ver") %>
          <% end %>
          <%= link_to edit_cliente_path(cliente), class: "btn btn-xs btn-default" do %>
            <%= fa_icon("pencil", text: "Editar") %>
          <% end %>
          <%= link_to cliente, class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "¿Seguro de eliminar este cliente?"} do %>
            <%= fa_icon("trash-o", text: "Eliminar") %>
          <% end %>
        </div>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to new_cliente_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "Nuevo Cliente") %>
<% end %>

app/views/clientes/new.html.erb
<% provide(:title, "Nuevo cliente") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/clientes/show.html.erb
<% provide(:title) do %>
  <%= @cliente.nombre %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Nombre</th>
      <td><%= @cliente.nombre %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Logo</th>
      <td><%= image_tag @cliente.logo %></td>
    </tr>
  </tbody>
</table>

<%= render 'redes/index', '@redes': @cliente.redes %>

<p>
  <%= link_to "Editar", edit_cliente_path(@cliente), class: "btn btn-primary" %>
  <%= link_to "Atrás", clientes_path, class: "btn btn-link" %>
  <%= link_to "Nueva red", new_cliente_red_path(@cliente), class: "btn btn-success" %>
</p>