config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  # Solo para usuarios autenticados (todo el sitio)


  authenticated :user do
    get 'calendario/index'
    get "/clientes/:cliente_id/redes/:red_id/posts", to: "posts#by_red"
    get "/posts", to: "posts#index"
    # get "/posts.json", to: "posts#index_json"
    resources :clientes do
      resources :redes do
        resources :posts
      end
    end
    resources :redes
    post '/posts/create/ig', to: 'posts#create_ig'
    put '/posts/:id/edit/ig', to: 'posts#update_ig'
    delete '/posts/:id/delete/ig', to: 'posts#destroy_ig'
    post "/post_test/:id", to: "posts#post_test"
    post "/post_imagen/:id", to: "posts#imagen_url"
    root to: "clientes#index" # , as: :authenticated_root
    # mount Sidekiq::Web => "/sidekiq" # monitoring console
  end

  # Si no esta autenicado
  root to: redirect("/users/sign_in")

  # Saco esta regla porque trae conflictos con los URL de blobs de Active Storage
  # match "*unmatched", to: "errors#route_not_found", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/redes_controller.rb
# == Schema Information
#
# Table name: redes
#
#  cliente_id     :bigint(8)
#  created_at     :datetime         not null
#  id             :bigint(8)        not null, primary key
#  nombre         :string           default(""), not null
#  nombre_display :string
#  pass           :string
#  tipo           :integer          default(0), not null
#  token          :string
#  updated_at     :datetime         not null
#  user           :string
#
# Indexes
#
#  index_redes_on_cliente_id  (cliente_id)
#
# Foreign Keys
#
#  fk_rails_...  (cliente_id => clientes.id)
#

class RedesController < ApplicationController
  before_action :set_red, only: %i[show edit update destroy]

  # GET /redes
  def index
    @redes = Red.all.order(:cliente_id)
  end

  # GET /redes/1
  def show
  end

  # GET /redes/new
  def new
    @red = Red.new
    @cliente = Cliente.find(params[:cliente_id])
  end

  # GET /redes/1/edit
  def edit
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base.slice(0, 32))
    @red.pass = crypt.decrypt_and_verify(@red.pass)
  end

  # POST /redes
  def create
    @red = Red.new(red_params)

    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base.slice(0, 32))
    @red['pass'] = crypt.encrypt_and_sign(red_params['pass'])

    if @red.save
      redirect_to @red, notice: 'Red fue creado satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /redes/1
  def update

    pars = red_params

    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base.slice(0, 32))
    pars['pass'] = crypt.encrypt_and_sign(red_params['pass'])

    if @red.update(pars)
      redirect_to @red, notice: 'Red fue guardado satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /redes/1
  def destroy
    @red.destroy
    redirect_to redes_url, notice: 'Red fue eliminado satisfactoriamente.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_red
    @red = Red.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def red_params
    params.require(:red).permit(:tipo, :token, :nombre, :nombre_display, :cliente_id, :user, :pass)
  end
end

app/views/redes/_form.html.erb
<%= bootstrap_form_for(@red) do |f| %>

  <%= f.alert_message "Han ocurrido los siguientes problemas:" %>

  <% unless @red.persisted? %>
    <%= f.hidden_field :cliente_id, value: @cliente.id %>
  <% else %>
    <h4><%= @red.cliente.nombre %></h4>
  <% end %>

  <%= f.select :tipo, REDES_TIPOS.map { |k, v| [k.capitalize, v] }, required: true, label: "Red"%>
  <div id="p_red_fb">
    <%= f.text_field :token %>
  </div>
  <div id="p_red_ig" style="display: none;">
    <%= f.text_field :user %>
    <%= f.text_field :pass, type: 'password' %>
  </div>
  <%= f.text_field :nombre %>
  <%= f.text_field :nombre_display %>

  <%= f.primary %>
  <%= link_to "Atrás", redes_path, class: "btn btn-link" %>

<% end %>

app/views/redes/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Nombre display</th>

      <th>Token</th>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Cliente</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @redes.each do |red| %>
      <tr>
        <td>
          <% imagen=red.tipo==0?"https://www.facebook.com/images/fb_icon_325x325.png":"https://instagram-brand.com/wp-content/uploads/2016/11/app-icon2.png" %>
          <%= image_tag(imagen, :alt => "rss feed", class:'icono-social') %>
        </td>
        <td>
          <%= link_to cliente_red_posts_path(red.cliente, red) do %>
            <%= red.nombre_display %>

          <% end %>
        </td>
        <td><%= red.token.blank?? '---' : red.token[0..10] + '...' %></td>
        <td><%= red.nombre %></td>
        <td>
          <%= red.tipo_cast %>
        </td>
        <td><%= red.cliente.nombre %></td>
        <td>
          <div class="btn-group">
            <%= link_to red, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Ver") %>
            <% end %>
            <%= link_to edit_red_path(red), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Editar") %>
            <% end %>
            <%= link_to red, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "¿Seguro de eliminar este red?" } do %>
              <%= fa_icon("trash-o", text: "Eliminar") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/redes/edit.html.erb
<%= javascript_pack_tag 'red' %>

<% provide(:title, "Editando red") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/redes/index.html.erb
<% provide(:title, "Lista de redes") %>

<%= render 'index', '@redes': @redes  %>

<br>

<%= link_to new_red_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "Nueva Red") %>
<% end %>

app/views/redes/new.html.erb
<%= javascript_pack_tag 'red' %>

<% @cliente.present?? provide(:title, "Nueva red de #{@cliente.nombre}") : provide(:title, "Nueva red") %>


<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/redes/show.html.erb
<% provide(:title) do %>
  <%= @red.cliente.nombre %> -
  <%= @red.nombre %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Tipo</th>
      <td><%= @red.tipo %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Token</th>
      <td>
          <div id="token"><%= @red.token%> </div>
      </td>
    </tr>
    <tr>
      <th class="col-sm-2">Nombre</th>
      <td><%= @red.nombre %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Nombre display</th>
      <td><%= @red.nombre_display %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Cliente</th>
      <td><%= @red.cliente.nombre %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to "Posts", cliente_red_posts_path(@red.cliente, @red), class: "btn btn-success" %>
  <%= link_to "Editar", edit_red_path(@red), class: "btn btn-primary" %>
  <%= link_to "Atrás", :back, class: "btn btn-link" %>
</p>